SYNOPSIS
========
   void throw(mixedÂ message)

DESCRIPTION
===========
   Abort execution. If the current program execution was initiated by 
   catch(E), that catch expression will return message(E) as error code.

   Calling `throw()` without an enclosing `catch()` does not make sense and 
   will result in a "Throw with no catch." error.

   USAGE
   =====
      This will just print the string "aborting execution":

         catch(throw("aborting execution"));

SEE ALSO
========
   catch(E), raise_error(E)
