SYNOPSIS
========
   void throw(mixedÂ arg)

DESCRIPTION
===========
   Abort execution. If the current program execution was initiated by catch(),
   that catch expression will return <arg> as error code.

   Calling throw() without previous catch() does not make sense and will 
   result in a "Throw with no catch." error.

   USAGE
   =====
      This will just print the string "aborting execution":

         catch(throw("aborting execution"));

SEE ALSO
========
   catch()(E), raise_error()(E)
